apiVersion: v1
kind: Deployment
metadata:
  name: html-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: html
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: html
        image: sid2104/html:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083